title: Type Time
description: A website with a blog about the history of typography over the years.
header_text: ""
footer_text: Copyright 2020 Abbie Tyler
header_feature_image: ../uploads/landing-image.png
bannerheight: 20vmax
logo: ../uploads/logo-type-time.jpg
favicon: ../uploads/android-chrome-512x512.png
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - name: About the author
    siteurl: /aboutme
