title: Typography Timeline
description: A website with a blog about the history of typography over the years.
header_text: Type Time
footer_text: Copyright 2020 Abbie Tyler
header_feature_image: ../uploads/pages.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
